apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm_chart.fullname" . }}
  labels:
    {{- include "helm_chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: graphql
      protocol: TCP
      name: graphql
  selector:
    app: {{ include "helm_chart.fullname" . }}
    {{- include "helm_chart.selectorLabels" . | nindent 4 }}
